<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sql_query_viewhelper"
 *
 * Auto generated by Extension Builder 2017-05-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'iCal',
    'description' => 'Provides TYPO3 Fluid ViewHelper to execute SQL Query from fluid template.',
    'category' => 'plugin',
    'author' => 'André Wuttig',
    'author_email' => 'andr.wuttig@gmail.com',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.18-7.99.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ]
];